name       : docker-compose
version    : 1.25.0_rc2
release    : 20
source     :
    - https://github.com/docker/compose/archive/1.25.0-rc2.tar.gz : 3b8b8f5ef64a5dc3bf3adc0c67948f18db30e960d00f8a452903e1231d64b709
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python3)
    - python-cached-property
    - python-docker-py
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-paramiko
    - python-pytest
    - python-texttable
rundeps    :
    - docker
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-dockerpty
    - python-docopt
    - python-paramiko
    - python-jsonschema
    - python-texttable
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-PyYAML-5.1.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 contrib/completion/bash/docker-compose $installdir/usr/share/bash-completion/completions/docker-compose
    install -Dm00644 contrib/completion/zsh/_docker-compose $installdir/usr/share/zsh/site-functions/_docker-compose
