name       : docker-compose
version    : 1.22.0
release    : 13
source     :
    - https://github.com/docker/compose/archive/1.22.0.tar.gz : d28a2e96976dae306f480f656e4487a0334a5f95c456408f4bbe4acc5760ffa0
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-docker-pycreds
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-requests
    - python-six
    - python-texttable
    - python-websocket-client
    - pyyaml
setup      : |
    %python3_setup
install    : |
    %python3_install
