name       : docker-compose
version    : 2.21.0
release    : 38
source     :
    - https://github.com/docker/compose/archive/refs/tags/v2.21.0.tar.gz : 0014b23382a50c90f91849e491500568366052882e22011822ca2d8a3b2976f2
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
networking : yes
builddeps  :
    - golang
rundeps    :
    - docker
environment: |
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"

    export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -ldflags=-X=github.com/docker/compose/v2/internal.Version=v$version -mod=readonly -modcacherw"

    export _cli_plugins_dir=/usr/lib/docker/cli-plugins
build      : |
    CGO_ENABLED=0 go build -trimpath -tags "e2e,kube" -o compose ./cmd
install    : |
    install -Ddm00755 $installdir/$_cli_plugins_dir
    install -m00755 compose $installdir/$_cli_plugins_dir/docker-compose

    # Compatibility symlink
    install -Ddm00755 "$installdir/usr/bin"
    ln -sf /usr/lib/docker/cli-plugins/docker-compose "$installdir/usr/bin/docker-compose"
