name       : docker-compose
version    : 1.13.0
release    : 8
source     :
    - https://github.com/docker/compose/archive/1.13.0.tar.gz : 0cace4a814cf629689f1738fc221eb0de12f6336ee682b8c9539568f63cf6785
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-docker-pycreds
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-requests
    - python-six
    - python-texttable
    - python-websocket-client
    - pyyaml
setup      : |
    %python3_setup
install    : |
    %python3_install
