name       : docker-compose
version    : 1.10.0
release    : 5
source     :
    - https://github.com/docker/compose/archive/1.10.0.tar.gz : 0277930feaeb03f480914274f65eb419a2ee4b48be9a9fb55a201bb3a14bf290
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-cached-property
    - python-docker-py
    - python-docker-pycreds
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-requests
    - python-six
    - python-texttable
    - python-websocket-client
    - python3-colorama
setup      : |
    %python3_setup
install    : |
    %python3_install
