name       : docker-compose
version    : 1.23.2
release    : 17
source     :
    - https://github.com/docker/compose/archive/1.23.2.tar.gz : 18ff12f80e21011e76e04d2579745224316e232a5ca94c79a2865dac5c66eef6
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python3)
    - python-cached-property
    - python-docker-py
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-pytest
    - python-texttable
rundeps    :
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-texttable
    - pyyaml
setup      : |
    #TEMP: This should be dropped with next version update
    %patch -p1 < $pkgfiles/0001-Remove-upper-bound-constraint-on-requests.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 contrib/completion/bash/docker-compose $installdir/usr/share/bash-completion/completions/docker-compose
    install -Dm00644 contrib/completion/zsh/_docker-compose $installdir/usr/share/zsh/site-functions/_docker-compose
check      : |
    %python3_test py.test3 -v tests/unit
