name       : docker-compose
version    : 1.9.0
release    : 3
source     :
    - https://github.com/docker/compose/archive/1.9.0.tar.gz : 5fdbf321e3a66c4de6d2c0e61a7504247aaf3304d6d41c557ce9131d20b0bd80
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-cached-property
    - python-docker-py
    - python-docker-pycreds
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-requests
    - python-six
    - python-texttable
    - python-websocket-client
setup      : |
    %python3_setup
install    : |
    %python3_install
