name       : docker-compose
version    : 1.23.1
release    : 15
source     :
    - https://github.com/docker/compose/archive/1.23.1.tar.gz : 843a458d366ca1d41ceec08b3387ba55c6953eba3a171d6af90db0b01f494312
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-docker-pycreds
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-requests
    - python-six
    - python-texttable
    - python-websocket-client
    - pyyaml
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 contrib/completion/bash/docker-compose $installdir/usr/share/bash-completion/completions/docker-compose
    install -Dm00644 contrib/completion/zsh/_docker-compose $installdir/usr/share/zsh/site-functions/_docker-compose
