name       : docker-compose
version    : 1.25.0_rc1
release    : 18
source     :
    - https://github.com/docker/compose/archive/1.25.0-rc1.tar.gz : 2a70b02f25f996c473d1dd119b3bbdc6a89bac5c6ea57926772ebc79b9703b20
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python3)
    - python-cached-property
    - python-docker-py
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-paramiko
    - python-pytest
    - python-texttable
rundeps    :
    - docker
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-dockerpty
    - python-docopt
    - python-paramiko
    - python-jsonschema
    - python-texttable
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 contrib/completion/bash/docker-compose $installdir/usr/share/bash-completion/completions/docker-compose
    install -Dm00644 contrib/completion/zsh/_docker-compose $installdir/usr/share/zsh/site-functions/_docker-compose
