name       : docker-compose
version    : 1.14.0
release    : 9
source     :
    - https://github.com/docker/compose/archive/1.14.0.tar.gz : 61d9e9669e1402f77320fbda4e9d3584c201781a9a6061b54a6786f5dcde888f
license    : Apache-2.0
component  : virt
summary    : A tool for defining and running multi-container Docker applications.
description: |
    Compose is a tool for defining and running multi-container Docker applications.
    With Compose, you use a Compose file to configure your application’s services. Then, using a single command, you create and start all the services from your configuration.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-cached-property
    - python-colorama
    - python-docker-py
    - python-docker-pycreds
    - python-dockerpty
    - python-docopt
    - python-jsonschema
    - python-requests
    - python-six
    - python-texttable
    - python-websocket-client
    - pyyaml
setup      : |
    %python3_setup
install    : |
    %python3_install
